name: tbib_flutter_icons
description: Customizable Icons for Flutterï¼Œyou can use with over 3K+ icons in your flutter project
version: 0.0.1
author: flutter-studio<2534290808@qq.com>
homepage: https://github.com/flutter-studio/flutter-icons.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
      # - family: Ionicons
      #   fonts:
      #     - asset: assets/fonts/Ionicons.ttf
      # - family: AntDesign
      #   fonts:
      #     - asset: assets/fonts/AntDesign.ttf
      # - family: FontAwesome
      #   fonts:
      #     - asset: assets/fonts/FontAwesome.ttf
      # - family: MaterialIcons
      #   fonts:
      #     - asset: assets/fonts/MaterialIcons.ttf
      # - family: Entypo
      #   fonts:
      #     - asset: assets/fonts/Entypo.ttf
      # - family: EvilIcons
      #   fonts:
      #     - asset: assets/fonts/EvilIcons.ttf
      # - family: Feather
      #   fonts:
      #     - asset: assets/fonts/Feather.ttf
      # - family: Foundation
      #   fonts:
      #     - asset: assets/fonts/Foundation.ttf
      # - family: MaterialCommunityIcons
      #   fonts:
      #     - asset: assets/fonts/MaterialCommunityIcons.ttf
      # - family: Octicons
      #   fonts:
      #     - asset: assets/fonts/Octicons.ttf
      # - family: SimpleLineIcons
      #   fonts:
      #     - asset: assets/fonts/SimpleLineIcons.ttf
      # - family: Zocial
      #   fonts:
      #     - asset: assets/fonts/Zocial.ttf
      # - family: FontAwesome5
      #   fonts:
      #     - asset: assets/fonts/FontAwesome5_Regular.ttf
      # - family: FontAwesome5_Brands
      #   fonts:
      #     - asset: assets/fonts/FontAwesome5_Brands.ttf
      # - family: FontAwesome5_Solid
      #   fonts:
      #     - asset: assets/fonts/FontAwesome5_Solid.ttf
      # - family: WeatherIcons
      #   fonts:
      #  
       fonts: 
        - family: Bytesize
          fonts:
            - asset: assets/fonts/Bytesize.ttf

        
        - family:  FontAwsome5Brands
          fonts:
          - asset: fonts/FontAwsome5Brands.ttf

        - family:  FontAwsome5Regular
          fonts:
          - asset: fonts/FontAwsome5Regular.ttf

          

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
